services:
  # ---------- Application ----------
  auth-service:
    image: pasarly-auth-service
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: ${SERVER_GRPC_HOST}
    networks:
      - pasarly-net
    restart: unless-stopped
    env_file:
      - .env
      - ../../.env
    depends_on:
      auth-database:
        condition: service_healthy
      auth-migrator:
        condition: service_completed_successfully

  # ---------- Database ----------
  auth-database:
    image: postgres:16-alpine
    container_name: ${DATABASE_HOST}
    networks:
      - pasarly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      retries: 5

  # ---------- Migrator ----------
  auth-migrator:
    image: pasarly-auth-migrator
    build:
      context: .
      dockerfile: Dockerfile.migrator
    container_name: auth-migrator
    networks:
      - pasarly-net
    restart: "no"
    env_file:
      - .env
    depends_on:
      auth-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${DATABASE_HOST}"]
      interval: 10s
      retries: 3

networks:
  pasarly-net:
    external: true

volumes:
  auth-db-data:
